27/11/22 (17:44:00) | ERROR: Input thread failed with exception: (5, 'Input/output error')
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 954, in _get_key
    with Raw(sys.stdin):
  File "/usr/bin/bpytop", line 798, in __exit__
    termios.tcsetattr(self.stream, termios.TCSANOW, self.original_stty)
termios.error: (5, 'Input/output error')
06/02/23 (18:36:20) | ERROR: Exception when sending signal 9 to pid 654
06/02/23 (18:36:20) | ERROR: [Errno 1] Operation not permitted
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 5479, in process_keys
    os.kill(pid, sig)
PermissionError: [Errno 1] Operation not permitted
06/02/23 (18:36:25) | ERROR: Input thread failed with exception: (5, 'Input/output error')
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 954, in _get_key
    with Raw(sys.stdin):
  File "/usr/bin/bpytop", line 798, in __exit__
    termios.tcsetattr(self.stream, termios.TCSANOW, self.original_stty)
termios.error: (5, 'Input/output error')
